MvcApplication1/Controllers/ComentarioController.cs
using MvcApplication1.Models;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace MvcApplication1.Controllers
{
    public class ComentarioController : Controller
    {
        private MyConnectionString db = new MyConnectionString();

        //
        // GET: /Comentario/

        public ActionResult Index()
        {
            var comentario = db.comentario.Include(c => c.restaurante);
            return View(comentario.ToList());
        }

        //
        // GET: /Comentario/Details/5

        public ActionResult Details(int id = 0)
        {
            comentario comentario = db.comentario.Find(id);
            if (comentario == null)
            {
                return HttpNotFound();
            }
            return View(comentario);
        }

        //
        // GET: /Comentario/Create

        public ActionResult Create()
        {
            ViewBag.cod_restaurante = new SelectList(db.restaurante, "cod", "nome");
            return View();
        }

        //
        // POST: /Comentario/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(comentario comentario)
        {
            if (ModelState.IsValid)
            {
                db.comentario.Add(comentario);
                db.SaveChanges();
            }

            ViewBag.cod_restaurante = new SelectList(db.restaurante, "cod", "nome", comentario.cod_restaurante);

            // Variável do tipo TemData utilizada para armazenar o valor temporário entre os controllers
            int idreturn = (int)TempData["id1"];

            //var id = db.restaurante.AsParallel(new SelectList(db.restaurante, "cod");
            return RedirectToAction("Details", "Home", new { id = idreturn });
        }

        //
        // GET: /Comentario/Edit/5

        public ActionResult Edit(int id = 0)
        {
            comentario comentario = db.comentario.Find(id);
            if (comentario == null)
            {
                return HttpNotFound();
            }
            ViewBag.cod_restaurante = new SelectList(db.restaurante, "cod", "nome", comentario.cod_restaurante);
            return View(comentario);
        }

        //
        // POST: /Comentario/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(comentario comentario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comentario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.cod_restaurante = new SelectList(db.restaurante, "cod", "nome", comentario.cod_restaurante);
            return View(comentario);
        }

        //
        // GET: /Comentario/Delete/5

        public ActionResult Delete(int id = 0)
        {
            comentario comentario = db.comentario.Find(id);

            if (comentario == null)
            {
                return HttpNotFound();
            }
            db.comentario.Remove(comentario);
            db.SaveChanges();
            //return RedirectToAction("Details", "Home");
            return RedirectToAction("Index");
        }

        //
        // POST: /Comentario/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            comentario comentario = db.comentario.Find(id);
            db.comentario.Remove(comentario);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcApplication1/Controllers/HomeController.cs
using MvcApplication1.Models;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace MvcApplication1.Controllers
{
    public class HomeController : Controller
    {
        private MyConnectionString db = new MyConnectionString();

        //
        // GET: /Home/

        // Autocomplete Textbox Using Database Return Value in ASP.NET Mvc3/Mvc4 Razor With Jquery
        public JsonResult AutoComplete(string Nome)
        {
            //private SchoolContext db = new SchoolContext();
            //var sugestao = from s in db.restaurante
            //               select s.nome;
            //var listaNomes = sugestao.Where(n => n.ToLower().StartsWith(Nome.ToLower()));

            //return Json(listaNomes, JsonRequestBehavior.AllowGet);

            var result = (from r in db.restaurante
                          where r.nome.ToLower().Contains(Nome.ToLower())
                          select new { r.nome }).Distinct();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Index()
        {
            //return View(db.restaurante.ToList());
            var data = db.restaurante.ToList();
            return View(data);
        }

        // Index com filtro
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(string Nome)
        {
            if (Nome == null || Nome == "")
            {
                var data = db.restaurante.ToList();
                return View(data);
            }
            else
            {
                var data = (from c in db.restaurante
                            where c.nome.Contains(Nome)
                            select c);
                return View(data);
            }

            //If Not String.IsNullOrEmpty(strCriterio) Then
            //    estudantes = estudantes.
            //                 Where(Function(est) est.SobreNome.ToUpper().Contains(strCriterio.ToUpper()) _
            //                 OrElse est.Nome.ToUpper().Contains(strCriterio.ToUpper()))
            //End If

            //return View(db.restaurante.ToList());
            //var data = db.restaurante.ToList();
        }

        private restaurante reg = new restaurante();

        public FileContentResult RecuperaImagem(int id)
        {
            reg = db.restaurante.FirstOrDefault(i => i.cod == id);
            if (reg.imagem != null)
            {
                return File(reg.imagem, "image/jpeg");
            }
            else
            {
                return null;
            }
        }

        //
        // GET: /Home/Details/5

        public ActionResult Details(int id = 0)
        {
            restaurante restaurante = db.restaurante
              .Include(i => i.comentario)
              .SingleOrDefault(x => x.cod == id);

            TempData["id1"] = (int)id;

            //restaurante restaurante = db.restaurante.Find(id);
            if (restaurante == null)
            {
                return HttpNotFound();
            }
            return View(restaurante);
        }

        //
        // GET: /Home/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Home/Create
        [HttpPost]
        // PROTEGE CONTRA REQUISIÇÕES INDEVIDAS
        [ValidateAntiForgeryToken]
        public ActionResult Create(restaurante rest) //, HttpPostedFileBase file
        {
            if (ModelState.IsValid)
            {
                if (Request.Files.Count > 0)
                {
                    int tamanho = (int)Request.Files[0].InputStream.Length;
                    byte[] arquivo = new byte[tamanho];
                    Request.Files[0].InputStream.Read(arquivo, 0, tamanho);
                    byte[] arquivoAR = arquivo;
                    rest.imagem = arquivoAR;
                }

                db.restaurante.Add(rest);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(rest);
        }

        //
        // GET: /Home/Edit/5
        public ActionResult Edit(int id = 0)
        {
            restaurante restaurante = db.restaurante.Find(id);
            if (restaurante == null)
            {
                return HttpNotFound();
            }
            return View(restaurante);
        }

        //
        // POST: /Home/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(restaurante restaurante)
        {
            if (ModelState.IsValid)
            {
                if (Request.Files.Count > 0)
                {
                    int tamanho = (int)Request.Files[0].InputStream.Length;
                    byte[] arquivo = new byte[tamanho];
                    Request.Files[0].InputStream.Read(arquivo, 0, tamanho);
                    byte[] arquivoAR = arquivo;
                    restaurante.imagem = arquivoAR;
                }

                db.Entry(restaurante).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(restaurante);
        }

        //
        // GET: /Home/Delete/5

        public ActionResult Delete(int id = 0)
        {
            restaurante restaurante = db.restaurante.Find(id);
            if (restaurante == null)
            {
                return HttpNotFound();
            }
            return View(restaurante);
        }

        //
        // POST: /Home/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            restaurante restaurante = db.restaurante.Find(id);
            db.restaurante.Remove(restaurante);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcApplication1/Views/Home/Create.cshtml
@model MvcApplication1.Models.restaurante

@{
    ViewBag.Title = "Criar novo registro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="titulo">
    <h1>Criar novo registro</h1>
</div>
<div class="principal">
    @using (Html.BeginForm("Create", "Home", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <div class="editor-label">
            @Html.LabelFor(model => model.nome)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.nome)
            @Html.ValidationMessageFor(model => model.nome)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.tipo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.tipo)
            @Html.ValidationMessageFor(model => model.tipo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.estilo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.estilo)
            @Html.ValidationMessageFor(model => model.estilo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.horario)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.horario)
            @Html.ValidationMessageFor(model => model.horario)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.endereço)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.endereço)
            @Html.ValidationMessageFor(model => model.endereço)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.bairro)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.bairro)
            @Html.ValidationMessageFor(model => model.bairro)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.cidade)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.cidade)
            @Html.ValidationMessageFor(model => model.cidade)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.descricao)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.descricao)
            @Html.ValidationMessageFor(model => model.descricao)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.avaliacao)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.avaliacao)
            @Html.ValidationMessageFor(model => model.avaliacao)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.imagem)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.imagem)
            @Html.ValidationMessageFor(model => model.imagem)
            <input type="file" name="Arquivo" />
        </div>

        <p>
            <input type="submit" value="Criar" />
        </p>
    }
</div>
<div class="finalItem">
    @Html.ActionLink("Retornar a Lista", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication1/Views/Home/Delete.cshtml
@model MvcApplication1.Models.restaurante

@{
    ViewBag.Title = "Apagar um registro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="titulo">
    <h1>Apagar registro</h1>
</div>

<div class="secundario">
    <div class="display-label">
        @Html.DisplayNameFor(model => model.cod)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.cod)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.nome)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.nome)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.tipo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.tipo)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.estilo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.estilo)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.horario)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.horario)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.endereço)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.endereço)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.bairro)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.bairro)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.cidade)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.cidade)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.descricao)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.descricao)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.avaliacao)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.avaliacao)
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <p>
            <input type="submit" value="Apagar" />
            |
            @Html.ActionLink("Retornar a Lista", "Index")
        </p>
    }
</div>

MvcApplication1/Views/Home/Details.cshtml
@model MvcApplication1.Models.restaurante
@{
    ViewBag.Title = "Exibir detalhes do registro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="titulo">
    <h1>Detalhes do restaurante</h1>
</div>
<div class="secundario">
    <div class="display-field">
        <img width="620" height="186" src="data:image/jpg;base64,@(Convert.ToBase64String(@Model.imagem))" alt="" />
    </div>

    <div class="display-label">
        @Html.DisplayFor(model => model.nome)
    </div>

    <div class="display-label">
        Tipo: @Html.DisplayFor(model => model.tipo)
    </div>

    <div class="display-label">
        Estilo: @Html.DisplayFor(model => model.estilo)
    </div>

    <div class="display-label">
        Horário de Funcionamento: @Html.DisplayFor(model => model.horario)
    </div>

    <div class="display-label">
        Endereço: @Html.DisplayFor(model => model.endereço)
    </div>

    <div class="display-label">
        Bairro: @Html.DisplayFor(model => model.bairro)
    </div>

    <div class="display-label">
        Cidade: @Html.DisplayFor(model => model.cidade)
    </div>
    <br />
    <div class="display-label">
        @Html.DisplayFor(model => model.descricao)
    </div>
</div>
<div class="finalDetalhe">
    <p>
        @Html.ActionLink("Editar registro", "Edit", new { id = Model.cod }) |
        @Html.ActionLink("Apagar registro", "Delete", new { id = Model.cod }) |
        @Html.ActionLink("Retornar a Lista", "Index") |
    </p>
</div>
<div class="finalComentario">
    <div class="display-label-c">
        <h2>Comentários:</h2>
        @Html.Partial("PartialComentario", Model.comentario)
    </div>
</div>

MvcApplication1/Views/Home/Edit.cshtml
@model MvcApplication1.Models.restaurante

@{
    ViewBag.Title = "Editar um registro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="titulo">
    <h1>Editar registro</h1>
</div>
<div class="principal">
    @using (Html.BeginForm("Edit", "Home", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <div class="editor-label">
            @Html.LabelFor(model => model.cod)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.cod)
            @Html.ValidationMessageFor(model => model.cod)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.nome)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.nome)
            @Html.ValidationMessageFor(model => model.nome)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.tipo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.tipo)
            @Html.ValidationMessageFor(model => model.tipo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.estilo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.estilo)
            @Html.ValidationMessageFor(model => model.estilo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.horario)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.horario)
            @Html.ValidationMessageFor(model => model.horario)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.endereço)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.endereço)
            @Html.ValidationMessageFor(model => model.endereço)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.bairro)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.bairro)
            @Html.ValidationMessageFor(model => model.bairro)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.cidade)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.cidade)
            @Html.ValidationMessageFor(model => model.cidade)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.descricao)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.descricao)
            @Html.ValidationMessageFor(model => model.descricao)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.avaliacao)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.avaliacao)
            @Html.ValidationMessageFor(model => model.avaliacao)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.imagem)
        </div>
        <div class="editor-field">

            @Html.ValidationMessageFor(model => model.imagem)
            <input type="file" name="Arquivo" />
        </div>

        <p>
            <input type="submit" value="Salvar" />
            | @Html.ActionLink("Retornar a Lista", "Index")
        </p>
    }
</div>
<br />

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication1/Views/Home/Index.cshtml
@model IEnumerable<MvcApplication1.Models.restaurante>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryui")

@{
    ViewBag.Title = "Pagina inicial - Exibe um registro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="titulo">
    <h1>Lista de Restaurantes</h1>
</div>
<div class="linkNovo">
    @Html.ActionLink("Criar novo registro", "Create")
</div>
@using (Html.BeginForm("Index", "Home", FormMethod.Post, new { }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="textbox">
        <p>
            Localizar por nome: @Html.TextBox("Nome")
            <input type="submit" value="Filtrar" title="" />
        </p>
    </div>
}

<div class="principal">
    <table>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.imagem)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.tipo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.estilo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.bairro)
            </th>

            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <img width="270" height="105" src='@(Url.Action("RecuperaImagem", "Home", new { id = item.cod }))' />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tipo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.estilo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.bairro)
                </td>

                <td>
                    @Html.ActionLink("Detalhes", "Details", new { id = item.cod })
                </td>
            </tr>
        }
    </table>
</div>

MvcApplication1/Views/Home/PartialComentario.cshtml
@model IEnumerable<MvcApplication1.Models.comentario>
<div class="PartialComentario">
    @*<p>
        @ViewData["Name"]
    </p>*@
    @foreach (var item in Model)
    {
        <table>
            <tr>
                @Html.DisplayFor(modelItem => item.comentario1)
            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.usuario)
                </td>
            </tr>
        </table>
        <br />
    }
</div>
<div style="font-size: medium">
    <p>
        @Html.ActionLink("Inserir comentário", "Create", "Comentario")
    </p>
</div>